Study/yena
CBNU-Nnet/java-oop-practice pull request #7
Opened 2020-10-26 01:35 UTC by cathy192

Make Function & Test code

2020-11-14 10:05 UTC, dailyworker commented on src/main/java/domain/CardDeck.java
> +            for(int j=1;j<14;j++){
왜 0에서 1로 바꿨는지?

2020-11-14 10:16 UTC, dailyworker requested changes
코드리뷰 한 부분 참고해서 수정요청 드립니다.

2020-11-14 10:16 UTC, dailyworker commented on src/main/java/domain/CardDeck.java
> +        int index= cards.size()-1;
아마, index가 1부터 시작해서 `cards.size()-1` 로 세팅하여 카드를 뽑는 것으로 한 것 같아보임.
그러나 index 변수명이 맞는지 생각해볼 필요 있다고 봄.

이를테면, Cards를 일급 콜렉션으로 빼서 따로 처리를 한다던가, 하는게 더 좋아보임.
또한, `Math.random()*index+1` 같은 경우도 getCard 혹은 drawCard와 같은 메소드로 처리하는게 가독성이 좋다고 생각함.

2020-11-14 10:16 UTC, dailyworker commented on src/main/java/domain/Dealer.java
> +
`ArrayList<Card>` 의 경우 `Player` 나 `Dealer` 둘 다 사용하며, 혼용될 가능성이 높고, 자주 쓰는 콜렉션임.
이를 일급콜렉션화 하는 것이 좋아보임.

2020-11-14 10:16 UTC, dailyworker commented on src/main/java/domain/Player.java
> +
abstract 키워드를 왜 안썼는지? 

addCard의 경우 `Gamer` 만 사용하는데 이걸 인터페이스에 명시하는게 맞을지?

2020-11-14 10:16 UTC, dailyworker commented on src/main/java/domain/Rule.java
> +
BlackJack에서 draw인 경우에는 Delaer가 이기게 수정 필요

또한, `Dealer`인 경우에는 16점 이하면 더 받고, 17점 이상인 경우 안받아야하는데 해당 메소드는 어딨는지?

2020-11-14 10:16 UTC, dailyworker commented on src/test/java/domain/DealerTest.java
> +        }
해당 부분 `Rule` 부분에서 `Delaer`인 경우 처리하는 메소드를 생성하여 처리해야 되는 것이 더 나아보임.

2020-11-25 06:47 UTC, cathy192 commented
코드 리펙토링 진행

2020-12-01 06:59 UTC, dailyworker approved these changes
👍

2020-12-01 06:59 UTC, dailyworker commented on src/main/java/domain/CardDeck.java
> +    private static Cards cards;
Static으로 선언한 이유는?

2020-12-01 06:59 UTC, merged