Study/ojy
CBNU-Nnet/java-oop-practice pull request #8
Opened 2020-12-16 05:26 UTC by y7133

Modify all agian(일급컬렉션 추가)

2020-12-20 09:02 UTC, dailyworker requested changes
`Dealer` 쪽은 일급콜렉션을 잘 쓴거 같은데 어떤 곳에서는 이상하게 쓴 부분들이 보임.
또한, 메소드나 변수들의 네이밍이 명확하지 않은 부분들이 부분부분 보임.

개선사항으로 달아둔 코멘트들은 같이 한번 논의해보기로 하자.

2020-12-20 09:02 UTC, brewagebear commented on src/main/java/domain/CardDeck.java
> +    List<Card> card=new ArrayList<>();
일급 콜렉션 만들어놓고 왜 이걸로 쓰는지?

2020-12-20 09:02 UTC, brewagebear commented on src/main/java/domain/CardDeck.java
> +    List<Card>  cardList = new ArrayList<>();
이전 코멘트와 동일 일급콜렉션 사용해서 바꿔보자

2020-12-20 09:02 UTC, brewagebear commented on src/main/java/domain/Dealer.java
> +    List<Card> dealerCardList= new ArrayList<>();
Cards 일급 콜렉션 내에 `getPlayerCard()` 와 같이 메소드를 넣어서 처리하는게 더 깔끔하지 않을까? 생각이 듦. 

아주 단순하게 짜보면

```java

public List<Card> getPlayerCards() {
    List<Card> playerCards = cards.toArrayList();
    return playerCards
}

```

2020-12-20 09:02 UTC, brewagebear commented on src/main/java/domain/Rule.java
> +            sum+=cardList.getCards().get(i).getPattern().getScore();
엔티티 그래프 `get(i).getPattern().getScore()` 이 부분을 좀 더 줄일 수 있는 방법을 같이 고민해봐도 좋을거같음.

2020-12-20 09:02 UTC, brewagebear commented on src/main/java/domain/Rule.java
> +    private int isOver(int sum){
method 명 직관성이 떨어짐 over가 어떤걸 의미하는지 명확하게 네이밍 필요

2020-12-20 09:02 UTC, dailyworker commented on src/main/java/domain/Cards.java
>          this.cards=cards;
이렇게 쓰면 불변성이 깨짐 예제들 다시 참고해보셈.
https://jojoldu.tistory.com/412

2020-12-21 04:56 UTC, y7133 commented on src/main/java/domain/CardDeck.java
> +    List<Card> card=new ArrayList<>();
저렇게 만들어주고 일급컬렉션의 생성자에 넣어주는데, 이렇게 안하면 static으로 해야하지 않나요?저번에 static으로 하면안된다고 해서...

2020-12-21 05:02 UTC, y7133 commented on src/main/java/domain/Cards.java
>          this.cards=cards;
앞에 public붙였습니다

2020-12-21 05:05 UTC, y7133 commented on src/main/java/domain/Rule.java
> +    private int isOver(int sum){
exceededTotal로 고쳤습니다

2020-12-21 05:05 UTC, y7133 commented on src/main/java/domain/Rule.java
> +            sum+=cardList.getCards().get(i).getPattern().getScore();
그 값만 찾아오는 메소드를 추가하였습니다

2020-12-22 12:46 UTC, y7133 commented
modify all domain

2021-01-04 13:49 UTC, dailyworker commented
코드 반영 제대로 안되서 다시 PR하기로 함

2021-01-04 13:49 UTC, closed without merging